name: chat_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  random_string: ^2.3.1
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1
  connectivity_plus: ^4.0.2
  flutter_chat_bubble: ^2.0.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  voice_message_package: ^2.2.1
  swipe_to: ^1.0.6
  photo_view: ^0.15.0
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.7.0
  firebase_storage: ^12.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
